config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  resources :contacts
  resources :documents
  resources :companies

  resources :jobs do
    patch :link_contact
    patch :link_document

    resources :contacts, module: 'jobs', only: [] do
      delete :unlink
    end

    resources :documents, module: 'jobs', only: [] do
      delete :unlink
    end
  end

  resources :tasks do
    patch :link_contact
    patch :link_document
    patch :link_job
    patch :link_company

    resources :contacts, module: 'tasks', only: [] do
      delete :unlink
    end

    resources :documents, module: 'tasks', only: [] do
      delete :unlink
    end    

    resources :jobs, module: 'tasks', only: [] do
      delete :unlink
    end

    resources :companies, module: 'tasks', only: [] do
      delete :unlink
    end
  end

  get '/contacts/:contact_id/add_reference', to: 'contacts#add_reference', as: 'add_reference'
  get '/contacts/sort', to: 'contacts#sort', as: 'contacts_sort'

  get '/jobs/:job_id/applied', to: 'jobs#applied', as: 'applied'
  get '/jobs/:job_id/archived', to: 'jobs#archived', as: 'archived'
  get '/jobs/:job_id/next', to: 'jobs#next', as: 'user_job_next'
  get '/jobs/:job_id/previous', to: 'jobs#previous', as: 'user_job_previous'
  
  get '/tasks/:task_id/completed', to: 'tasks#completed', as: 'completed'

  root 'static_pages#home'
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :user

  has_many :company_jobs
  has_many :companies, through: :company_jobs
  
  has_many :job_contacts
  has_many :contacts, through: :job_contacts

  has_many :job_documents
  has_many :documents, through: :job_documents
  
  has_many :task_jobs
  has_many :tasks, through: :task_jobs

  validates :company, :position, presence: true
  validates_associated :user

  scope :applied, -> { where("applied = ? ", true) }


  def next
    join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
    where_query = 'jobs.id > ? AND jobs.user_id = ?'

    job = Job.joins(join_query).where(where_query, id, user_id).first
    job ||= Job.find_by(user_id: user_id)
  end

  def previous
    join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
    where_query = 'jobs.id > ? AND jobs.user_id = ?'

    job = Job.joins(join_query).where(where_query, id, user_id).first
    job ||= Job.find_by(user_id: user_id)
  end
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user

  has_many :company_tasks
  has_many :companies, through: :company_tasks

  has_many :task_contacts
  has_many :contacts, through: :task_contacts

  has_many :task_documents
  has_many :documents, through: :task_documents
  
  has_many :task_jobs
  has_many :jobs, through: :task_jobs

  validates :title, presence: true
  validates_associated :user

  scope :completed_false, -> { where('completed = ?', false) }
  scope :completed_true, -> { where('completed = ?', true) }

  scope :overdue, -> { where('due_date < ?', DateTime.now.end_of_day) }
  scope :upcoming, -> { where('due_date >= ?', DateTime.now.beginning_of_day) }
  scope :today, -> { where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day) }
end

app/controllers/jobs/contacts_controller.rb
# frozen_string_literal: true
module Jobs
  class ContactsController < ApplicationController
    
    def unlink
      contact = Contact.find(params[:contact_id])
      job = Job.find(params[:job_id])
      job.contacts.delete(contact)
      respond_to do |format|
        format.json { render json: contact, status: 200 }
      end
    end
  end
end

app/controllers/jobs/documents_controller.rb
# frozen_string_literal: true
module Jobs
  class DocumentsController < ApplicationController
    

    def unlink
      document = Document.find(params[:document_id])
      job = Job.find(params[:job_id])
      job.documents.delete(document)
      respond_to do |format|
        format.json { render json: document, status: 200 }
      end
    end
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :set_job, except: %i[index filter new create]

  def index
    @jobs = current_user.jobs
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @jobs, status: 200 }
    end
  end
  
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @job, status: 200 }
    end
  end

  def next
    @next_job = @job.next
    respond_to do |format|
      format.html { redirect_to(job_path(@next_job)) }
      format.json { render json: @next_job }
    end
  end

  def previous
    @previous_job = @job.previous
    respond_to do |format|
      format.html { redirect_to(job_path(@previous_job)) }
      format.json { render json: @previous_job }
    end
  end

  def applied
    appStr = params[:q]
    appBool = appStr === 'true'
    @job.applied = appBool
    flash[:notice] = 'Applied status changed'
    @job.save
    respond_to do |format|
      format.json { render json: @job }
    end
  end

  def archived
    appStr = params[:q]
    appBool = appStr === 'true'
    @job.archived = appBool
    flash[:notice] = 'Archive status changed'
    @job.save
    respond_to do |format|
      format.json { render json: @job }
    end
  end

  def link_contact
    c_id = params[:job][:contact_ids]
    @contact = Contact.find(c_id)
    @job.contacts << @contact unless @job.contacts.include?(@contact)
    @job.save
    respond_to do |format|
      format.json { render json: @contact }
    end
  end

  def link_document
    d_id = params[:job][:document_ids]
    @document = Document.find(d_id)
    @job.documents << @document unless @job.documents.include?(@document)
    @job.save
    respond_to do |format| 
      format.json { render json: @document }
    end
  end

  def new
    @job = Job.new(user: current_user)
    @user = current_user
  end

  def create
    @job = Job.create(job_params)
    @job.user = current_user
    @job.archived = false
    @job.save
    redirect_to new_task_path(company: @job.company, position: @job.position)
  end





  def edit 
  end

  def update
    @job.update(job_params)
    flash[:notice] = 'Job updated'
    redirect_to job_path(@job)
  end

  def destroy
    @job.destroy
    flash[:notice] = 'Job destroyed'
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:company, :position, :date_posted, :closing_date, :job_desc, :co_desc, :url, :applied, :requirements, :notes, :archived)
  end  

  def set_job
    # binding.pry
    @job = Job.find(params[:id] || params[:job_id])
  end
end

app/controllers/tasks/jobs_controller.rb
# frozen_string_literal: true
module Tasks
  class JobsController < ApplicationController
    

    def unlink
      @job = Job.find(params[:job_id])
      task = Task.find(params[:task_id])
      task.jobs.delete(@job)
      respond_to do |format|
        format.json { render json: @job, status: 200 }
      end
    end
  end
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true

module JobsHelper
  def truncate_desc(desc)
    truncate_desc(desc, length: 10, omission: '...')
  end
end

app/views/jobs/_form.html.erb
<div id='new-job-form'>

    <%= form_for [@job] do |f| %>

            <div class="actions field">
                <%= f.button "SAVE POSITION" %>
            </div>

            <div class="field co-name">
                <%= f.label :company, "Company Name" %><br>
                <%= f.text_field :company, id: "company", :required => true  %>
            </div>

            <div class="field position">
                <%= f.label :position %><br>
                <%= f.text_field :position, id: "position", :required => true  %>
            </div>
           
            <div class="field posted-date" id="job-posted-date-field">
                <%= f.label :date_posted %><br>

                <% if defined?(@job.date_posted) %>
                    <%= f.date_field :date_posted, id: "date_posted" %>
                <% else %>
                    <%= f.date_field :date_posted, id: "date_posted", :value => Time.now.strftime('%m-%d-%Y') %>
                <% end %>

            </div>             

            <div class="field link">
                <%= f.label :url, "Link to Posting" %><br>
                <%= f.text_field :url, id: "url" %>
            </div> 


            <div class="field job-desc">
                <%= f.label :job_desc, "Job Description" %><br>
                <%= f.text_area :job_desc, {id: "job_desc", class: "field"}%>
            </div>            

            <div class="field co-desc">
                <%= f.label :co_desc, "Company Description" %><br>
                <%= f.text_area :co_desc, {id: "co_desc", class: "field"} %>
            </div>

            <div class="field requirements">
                <%= f.label :requirements, "Requirements" %><br>
                <%= f.text_area :requirements, {id: "requirements", class: "field"} %>
            </div>            

            <div class="field notes">
                <%= f.label :notes, "Notes" %><br>
                <%= f.text_area :notes, {id: "notes", class: "field"} %>
            </div>


    <% end %> <!-- close form -->

</div> 

app/views/jobs/_job.html.erb
<h3><%= link_to "<li>#{job.company} - #{job.position}</li><br>".html_safe, job_path(job), :class => "bullet-item" %></h3>

app/views/jobs/_job_task_dropdown.html.erb
<div>
	<%= form_for @task, url: task_link_job_path(@task), :html => {:id => "add-job", :class => "link-field", :method => :patch} do |f| %>

		<p><%= f.collection_select :job_ids, @task.user.jobs, :id, :company, {:include_blank => 'choose job'} %></p>	

		<%= f.submit "Link job", {id: 'btn-add-job', class: 'btn-add-task-item'} %>

	<% end %>
</div>

app/views/jobs/_table.html.erb
    <% if jobs.length > 0 %>

      <% table_class = jobs[0].archived ? 'archive-table job-table' : 'active-table job-table' %>

      <table class="<%= table_class %>">
        <tr class='job-index-header-row'>
          <th>Company</th>
          <th>Position</th>

          <% if jobs[0].archived == false %>
            <th class='mobile-no-show'>Date Posted</th>
            <th class='mobile-no-show mid-no-show'>Upcoming Tasks</th>
            <th>Next Task Due</th>
          <% end %>


          <th class='mobile-no-show'></th>
          <th class='mobile-no-show'></th>
        </tr>
        <% jobs.each do |job| %>

          <% if job.applied && !job.archived %>
            <% row_class = "applied active" %>
          <% elsif !job.applied && !job.archived %>
            <% row_class = "not-applied active" %>
          <% elsif job.applied && job.archived %>
            <% row_class = "applied archived" %>
          <% elsif !job.applied && job.archived %>
            <% row_class = "not-applied archived" %>
          <% end %>


          <tr class="<%= row_class %>" >

      	    <td class='company-td'><%= link_to job.company, job_path(job) %></td>
      	    <td class='position-td'><%= link_to job.position, job_path(job) %></td>


            <% if jobs[0].archived == false %>
        	    <td class='date-posted-td mobile-no-show'><%= format_date(job.date_posted) %></td>
              <td class='job-tasks-td mobile-no-show mid-no-show'><%= job.tasks.completed_false.length %> todos</td> 

              <% if job.tasks.length > 0 %> 
                <% next_task = job.tasks.first %>
                <td><%= link_to format_date(next_task.due_date), task_path(next_task) %></td>
              <% else %>
                <td>---</td>
              <% end %>
            <% end %>




      	    <td class='edit-td mobile-no-show'><%= link_to "Edit", edit_job_path(job) %></td>
      	    <td class='delete-td mobile-no-show'><%= link_to "Delete", job_path(job), :method => :delete %></td>
      	  </tr>
        <% end %>
      </table> <!-- close table -->
    <% end %>

app/views/jobs/edit.html.erb
<%= render 'form' %>

app/views/jobs/index.html.erb
<div id='job-index-container'>
  <% if @jobs.length > 0 %>

    <% @jobs_active = @jobs.select {|job| job.archived == false} %>

    <% @jobs_archived = @jobs.select {|job| job.archived == true} %>

    <h1>POSITIONS</h1>




    <div id='job-index-header'>


      <div><button><%= link_to "Add New Position", new_job_path %></button></div>

        <% if @jobs_archived.length > 0 %> 
          <div>
            <form>
              <input id='show-archive-check' type="checkbox" name="archive" value="1"> show archive
          </form>
        </div>
        <% end %>


      </div>

    <br>
    <br>






    <div id="active-wrapper">
      <%= render partial: "table", locals: {jobs: @jobs_active} %>
    </div>


    <div id="archive-wrapper" style="display: none;">
      <% if @jobs_archived.length > 0 %>
        <br><br>
        <h3>Archived Positions</h3>
        <%= render partial: "table", locals: {jobs: @jobs_archived} %>
      <% end %>
    </div>

  <% else %>
    <div id='top'>
      <h1>YOU HAVE NO SAVED POSITIONS</h1>
      <button><%= link_to "Add New Position", new_job_path %></button>
      <br><br>
    </div>
  <% end %>
</div> <!--close page-->








<script>


const renderArchive = function() {

var checkbox = document.querySelector("#show-archive-check");

  checkbox.addEventListener( 'change', function() {
    let archiveCheck = document.getElementById('show-archive-check').checked
      if(archiveCheck) {
          $('#archive-wrapper').show()
      } else {
          $('#archive-wrapper').hide()
      }
  });
    
}




$( document ).on('turbolinks:load', function() {
  renderArchive()
})


</script>

app/views/jobs/new.html.erb
<%= render 'form' %>

app/views/jobs/show.html.erb
<div class='user-id' data-id="<%= @job.user.id %>"></div>
<div class='job-id' data-id="<%= @job.id %>"></div>
<div id='job-show-wrapper' class='show-container'>
	<div class='heading-container'>
		<div class='edit-delete'>
			<td><%= link_to "Edit", edit_job_path(@job) %></td>
		    <td><%= link_to "Delete", job_path(@job), method: :delete %></td>
		</div>
	    <span class="headline pg-btn btn-previous"><i class="fa fa-long-arrow-left"></i></span>
	    <h1 id='job-company-position' class='headline'><%= @job.company %> - <%= @job.position %></h1>
		<span class="headline pg-btn btn-next"><i class="fa fa-long-arrow-right"></i></span>
	</div> <!-- close container -->

	<div id='dates-container'>
		<section id="job-date-section">
			<div><h3 class='posted-date'>Posted Date: <%= format_date(@job.date_posted) %></h3></div>
			<% if @job.closing_date != nil %>
				<div><h3> Closing Date: <%= @job.closing_date %></h3></div>
			<% end %>
			<div><h3 class='link-to'><a href="<%= @job.url %>" target="_blank">Go to Posting</a></h3></div>
		</section>
	</div> <!-- close container -->

	<div id='applied-container'>
		<section id='applied-section'>

			<div id='job-applied'></div>
			<div id='applied-toggle'>
				<input type="checkbox" id="switch">
				<label id='switch-label' for="switch">Toggle</label>
			</div>

			<div id='job-archived'></div>
			<div id='archived-toggle'>
				<input type="checkbox" id="switch-archived">
				<label id='switch-label' for="switch-archived">Toggle</label>
			</div>


		</section>
	</div> <!-- close container -->

	<div id='job-desc-container' class='job-content-container'>
		<% if @job.job_desc != "" %>
			<h2> Job Description </h2>
			<h3 class='descriptions'><%= @job.job_desc %></h3>
		<% else %>
			<h2>This job has no job description</h2>
			<p class='create-item'><%= link_to "add job description", edit_job_path(@job) %></p>
		<% end %>
	</div> <!-- close container -->

	<div id='job-co-container' class='job-content-container'>
		<% if @job.co_desc != "" %>
			<h2> Company Description </h2>
			<h3 class='descriptions'><%= @job.co_desc %></h3>
		<% else %>
			<h2>This job has no company description</h2>
			<p class='create-item'><%= link_to "add company description", edit_job_path(@job) %></p>
		<% end %>
	</div> <!-- close container -->

	<div id='job-reqs-container' class='job-content-container'>
		<% if @job.requirements != "" %>
			<h2> Requirements </h2>
			<h3 class='descriptions'><%= @job.requirements %></h3>
		<% else %>
			<h2>This job has no company requirements</h2>
			<p class='create-item'><%= link_to "add requirements", edit_job_path(@job) %></p>
		<% end %>
	</div> <!-- close container -->

	<div id='job-notes-container' class='job-content-container'>
		<% if @job.notes != "" %>
			<h2> Notes </h2>
			<h3 class='descriptions'><%= @job.notes %></h3>
		<% else %>
			<h2>This job has no company notes</h2>
			<p class='create-item'><%= link_to "add notes", edit_job_path(@job) %></p>
		<% end %>
	</div> <!-- close container -->

	<div class='linked-job-items'>
		<div class='link-doc-container link-container'>
			<div id='job-linked-docs'  class='job-linked-items'>
		    	<h2>LINKED DOCUMENTS</h2>
		    	<div id='job-documents'></div>
		    </div>

		    <div id='add-doc-link'>
	    		<%= render 'documents/document_dropdown' %>
	    	</div>
	    </div> <!-- close container -->

	    <div class='link-contact-container link-container'>
	    	<div id='job-linked-contacts' class='job-linked-items'>
		    	<h2>LINKED CONTACTS</h2>
		    	<div id='job-contacts'></div>
		    </div>

		    <div id='add-contact-link'>
				<%= render 'contacts/contact_dropdown' %>
			</div>
	    </div> <!-- close container -->

	    <div class='link-task-container link-container'>
	    	<h2>LINKED TASKS</h2>
			<% if @job.tasks.length > 0%>
				<!-- <div id='task-list'></div> -->
		    	<%= render partial: "tasks/task", collection: @job.tasks || "No Linked Tasks" %>
		    <% else %>
		    	<h3>You have no linked tasks</h3>
			<% end %>
			<p class='create-item'><%= link_to "create a task", new_task_path %></p>
	    </div> <!-- close container -->
	</div> <!-- close linked items -->
</div> <!-- close wrapper -->





<script>

var AUTH_TOKEN = $('meta[name=csrf-token]').attr('content');

//LISTENER FOR NEXT BUTTON - SENDS TO USER'S NEXT JOB
const nextButton = function() {
	$('.btn-next').on('click', function() {
		let nextPg = `/jobs/${job_id}/next`
		window.location.href = nextPg;
	})
}

//LISTENER FOR PREVIOUS BUTTON - SENDS TO USER'S PREVIOUS JOB
const previousButton = function() {
	$('.btn-previous').on('click', function() {		
		let previousPg = `/jobs/${job_id}/previous`
		window.location.href = previousPg;
	})
}

//RETRIEVE JOB DOCUMENTS, CREATE CONSTANT INSTANCE, APPEND DOCUMENTS
const getDocuments = function (data) {
    jQuery(data['documents']).each(function(i, document){
        let d = new Document(document, user_id)
        $("#job-documents").append(d.formatSpan())
    })
}

//RETRIEVE JOB CONTACTS, CREATE CONSTANT INSTANCE, APPEND CONTACTS
const getContacts = function (data) {
    jQuery(data['contacts']).each(function(i, contact){
        let c = new Contact(contact, user_id)
        $("#job-contacts").append(c.formatSpan())
    })
}





//CHANGE APPLIED STATUS USING TOGGLE
const toggleApplied = function (job) {
	// place click listener on toggle
	$('#switch').on('click', function() {
		// route changing to new status
	    job.applied = !job.applied;
	    $.get(`/jobs/${job_id}/applied?q=${job.applied}`, function(data) {
	    	$('#job-applied').html(job.appliedString(job.applied))
	    })
	})
}

//DISPLAY APPLIED STRING AND TOGGLE STATUS
const displayAppliedDetails = function (job) {
	// renders yes/no string to applied status
	$('#job-applied').html(job.appliedString())
	// identifies toggle element and positions according to status
	let tog = document.getElementById("switch")
	tog.checked = job.applied;
}





//CHANGE ARCHIVED STATUS USING TOGGLE
const toggleArchived = function (job) {
	// place click listener on toggle
	$('#switch-archived').on('click', function() {
		// route changing to new status
	    job.archived = !job.archived;
	    $.get(`/jobs/${job_id}/archived?q=${job.archived}`, function(data) {
	    	$('#job-archived').html(job.archivedString(job.archived))
	    })
	})
}

//DISPLAY ARCHIVED STRING AND TOGGLE STATUS
const displayArchivedDetails = function (job) {
	// renders yes/no string to archived status
	$('#job-archived').html(job.archivedString())
	// identifies toggle element and positions according to status
	let tog = document.getElementById("switch-archived")
	tog.checked = job.archived;
}





//BUTTON LISTENER, SEND PATCH W CONTACT TO CONTROLLER, 
const linkContact = function() {
	$('#btn-add-contact').on('click', function(e) {
		e.preventDefault()
		var form = $('#add-contact')
		var action = form.attr('action')
		var data = form.serialize()
		data.authenticity_token = AUTH_TOKEN;
		$.ajax({
			url: `/jobs/${job_id}/link_contact`, 
			data: data, 
			type: "PATCH",
			dataType: 'json',
            success: function (data) {
            	contact = new Contact(data, user_id)
				$("#job-contacts").append(contact.formatSpan())
                alert('success') 
            },
            error: function (data) {
            	console.log('fail')
            	console.log(data)
                alert('no success') }
        })
	})
}


//BUTTON LISTENER, SEND PATCH W DOCUMENT TO CONTROLLER, 
const linkDocument = function() {

	$('#add-document').on('submit', function(e) {
		e.preventDefault()
		var form = $('#add-document')
		var action = form.attr('action')
		var data = form.serialize()
		data.authenticity_token = AUTH_TOKEN;
		$.ajax({
		url: action,
		data: data,
		type: "PATCH", 
        success: function (data) {
        	doc = new Document(data, user_id)
			$("#job-documents").append(doc.formatSpan())
            alert('success') },
        error: function (data) {
            alert('no success') }
        })
	})
}



// REMOVE JOB CONTACT 
const unlinkContact = function() {

	$(document.body).on('click', 'span.remove-contact', function(e) {
		let contactId = this.id

		$.ajax({
			type: "DELETE", 
			url: `/jobs/${job_id}/contacts/${contactId}/unlink`,
			dataType: 'json',
			data: {authenticity_token: AUTH_TOKEN},

	        success: function (data) {
	        	console.log(data)
				let id = data['id']
		    	$("#contactItem-" + id).remove()
		    	$("#" + id).remove();
		    	$('.remove-contact.'+ id).remove()
		    },
	        error: function (data) {
	            alert('no success') }
	    })
	})
}

// BUTTON LISTENER, REMOVE JOB DOCUMENT 
const unlinkDocument = function() {

	$(document.body).on('click', 'span.remove-document', function(e) {
		let documentId = $(this).data('id')

		$.ajax({
			type: "DELETE", 
			url: `/jobs/${job_id}/documents/${documentId}/unlink`,
			data: {authenticity_token: AUTH_TOKEN},
			dataType: 'json',
	        success: function (data) {
				let id = data['id']
		    	$("#documentItem-" + id).remove()
		    	$("#" + id).remove();
		    },
	        error: function (data) {
	            alert('no success') }
	    })
	})
}

// OPEN DOC DROPDOWN SPAN
const docClick = function() {
	var clicks = 0

	$(document.body).on('click', "i.doc", function() {
		var id = this.id

	if (clicks % 2 == 0) {
		$('.document.'+id).css('display', 'block')
		clicks++
		}
	else {
		$('.document.'+id).css('display', 'none')
		clicks++
		} 
	});
}

// OPEN CONTACT DROPDOWN SPAN
const contactClick = function() {
	var clicks = 0

	$(document.body).on('click', "i.contact", function() {
		var id = this.id

	if (clicks % 2 == 0) {
		$('.contact.'+id).css('display', 'block')
		clicks++
		}
	else {
		$('.contact.'+id).css('display', 'none')
		clicks++
		} 
	});
}

$( document ).on('turbolinks:load', function() {
	user_id = $(".user-id").data("id")
	job_id = $(".job-id").data("id")

	$.get(`/jobs/${job_id}`, function(data) {
		console.log('after ajax finishes..')
		job = new Job(data, user_id)

	    displayAppliedDetails(job)  //injects string and toggle elements
		toggleApplied(job) //connects applied click listener	    

		displayArchivedDetails(job)  //injects string and toggle elements
		toggleArchived(job) //connects archived click listener

		getDocuments(data) //
		getContacts(data)

	    nextButton()
	    previousButton()

		linkContact()
		linkDocument()
		
		unlinkContact()
		unlinkDocument()

		docClick()
		contactClick()
	},'json'
	);
})

</script>