config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  resources :contacts
  resources :documents
  resources :companies

  resources :jobs do
    patch :link_contact
    patch :link_document

    resources :contacts, module: 'jobs', only: [] do
      delete :unlink
    end

    resources :documents, module: 'jobs', only: [] do
      delete :unlink
    end
  end

  resources :tasks do
    patch :link_contact
    patch :link_document
    patch :link_job
    patch :link_company

    resources :contacts, module: 'tasks', only: [] do
      delete :unlink
    end

    resources :documents, module: 'tasks', only: [] do
      delete :unlink
    end    

    resources :jobs, module: 'tasks', only: [] do
      delete :unlink
    end

    resources :companies, module: 'tasks', only: [] do
      delete :unlink
    end
  end

  get '/contacts/:contact_id/add_reference', to: 'contacts#add_reference', as: 'add_reference'
  get '/contacts/sort', to: 'contacts#sort', as: 'contacts_sort'

  get '/jobs/:job_id/applied', to: 'jobs#applied', as: 'applied'
  get '/jobs/:job_id/archived', to: 'jobs#archived', as: 'archived'
  get '/jobs/:job_id/next', to: 'jobs#next', as: 'user_job_next'
  get '/jobs/:job_id/previous', to: 'jobs#previous', as: 'user_job_previous'
  
  get '/tasks/:task_id/completed', to: 'tasks#completed', as: 'completed'

  root 'static_pages#home'
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :user
  
  has_many :job_contacts
  has_many :jobs, through: :job_contacts

  has_many :company_contacts
  has_many :companies, through: :company_contacts

  has_many :task_contacts
  has_many :tasks, through: :task_contacts

  scope :is_reference, -> { where('reference = ?', true) }

  validates :email, :first_name, presence: true
  validates_associated :user

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :user

  has_many :company_jobs
  has_many :companies, through: :company_jobs
  
  has_many :job_contacts
  has_many :contacts, through: :job_contacts

  has_many :job_documents
  has_many :documents, through: :job_documents
  
  has_many :task_jobs
  has_many :tasks, through: :task_jobs

  validates :company, :position, presence: true
  validates_associated :user

  scope :applied, -> { where("applied = ? ", true) }


  def next
    join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
    where_query = 'jobs.id > ? AND jobs.user_id = ?'

    job = Job.joins(join_query).where(where_query, id, user_id).first
    job ||= Job.find_by(user_id: user_id)
  end

  def previous
    join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
    where_query = 'jobs.id > ? AND jobs.user_id = ?'

    job = Job.joins(join_query).where(where_query, id, user_id).first
    job ||= Job.find_by(user_id: user_id)
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy add_reference]
  

  def index
    @contacts = current_user.contacts
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @contacts, status: 200 }
    end
  end

  def sort # THIS IS BEING READ AS A SHOW PAGE
    @contacts = current_user.contacts
    @contacts_sorted = @contacts.sort_by &:last_name
    respond_to do |format|
      format.json { render json: @contacts_sorted, status: 200 }
    end
  end

  def unlink_contact
    c_id = params[:contact_id]
    j_id = params[:job_id]
    contact = Contact.find(c_id)
    job = Job.find(j_id)
    job.contacts.delete(contact)
    # binding.pry
    respond_to do |format|
         format.json { render json: contact, status: 200 }
       end
  end

  def add_reference
    # binding.pry
    refStr = params[:q]
    refBool = refStr.to_s == 'true'
    @contact.reference = refBool
    flash[:notice] = 'Reference status has changed'
    @contact.save
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @contact, status: 200 }
    end
  end

  def new
    @contact = Contact.new(user: current_user)
    @contacts = current_user.contacts
  end

  def create
    @contact = Contact.create(contact_params)
    @contact.user = current_user
    @contact.save
    
    respond_to do |format|
      format.json { render json: { html: render_to_string('contacts/_contact.html.erb', layout: false, locals: { contact: @contact }) } }
    end
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @contact, status: 200 }
    end
  end

  def edit 
  end

  def update
    flash[:notice] = 'Contact updated'
    @contact.update(contact_params)
    redirect_to contact_path(@contact)
  end

  def destroy
    flash[:notice] = 'Contact destroyed'
    @contact.destroy
    redirect_to new_contact_path
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :workplace, :linkedin, :phone, :email, :reference, :notes)
  end

  def set_contact
    @contact = Contact.find(params[:id] || params[:contact_id])
  end
end

app/controllers/jobs/contacts_controller.rb
# frozen_string_literal: true
module Jobs
  class ContactsController < ApplicationController
    
    def unlink
      contact = Contact.find(params[:contact_id])
      job = Job.find(params[:job_id])
      job.contacts.delete(contact)
      respond_to do |format|
        format.json { render json: contact, status: 200 }
      end
    end
  end
end

app/controllers/tasks/contacts_controller.rb
# frozen_string_literal: true
module Tasks
  class ContactsController < ApplicationController
    

    def unlink
      # binding.pry
      contact = Contact.find(params[:contact_id])
      task = Task.find(params[:task_id])
      task.contacts.delete(contact)
      respond_to do |format|
        format.json { render json: contact, status: 200 }
      end
    end
  end
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
  def formatted_name(contact)
    "#{contact.first_name} #{contact.last_name}".titlecase
  end
end

app/views/contacts/_contact.html.erb
<h3 class='list-items'><%= link_to "<li>#{contact.first_name} #{contact.last_name}</li><br>".html_safe, contact_path(contact), :class => 'bullet-item' %></h3>

app/views/contacts/_contact_dropdown.html.erb
	

<%= form_for @job, :url => job_path(@job), :html => {:id => "add-contact", :class => "link-field", :method => :patch} do |f| %>

	<p><%= f.collection_select :contact_ids, @job.user.contacts, :id, :last_name, {:include_blank => 'choose contact'} %></p>	

	<%= f.submit "Link Contact", {id: 'btn-add-contact', class: 'btn-add-job-item'} %>

<% end %>

app/views/contacts/_contact_task_dropdown.html.erb
<%= form_for @task, :url => task_path(@task), :html => {:id => "add-contact", :method => :patch} do |f| %>

	<p><%= f.collection_select :contact_ids, @task.user.contacts, :id, :last_name, {:include_blank => 'choose contact'} %></p>	

	<%= f.submit "Link Contact", {id: 'btn-add-contact', class: 'btn-add-task-item'} %>

<% end %>

app/views/contacts/_form.html.erb
	
<%= form_for [@contact] do |f| %>

    <div class="field">
        <%= f.label :first_name, "First Name", :required => true  %><br>
        <%= f.text_field :first_name, id: "first-name" %>
    </div>

    <div class="field">
        <%= f.label :last_name, "Last Name" %><br>
        <%= f.text_field :last_name, id: "last-name", :required => true %>
    </div>

    <div class="field">
        <%= f.label :workplace %><br>
        <%= f.text_field :workplace, id: "workplace" %>
    </div>            

    <div class="field">
        <%= f.label :phone %><br>
        <%= f.text_field :phone, id: "phone" %>
    </div>

    <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, id: "email" %>
    </div>   

    <div class="field notes">
        <%= f.label :notes, "Notes" %><br>
        <%= f.text_area :notes, {id: "notes", class: "field"} %>
    </div>         


    <div class="actions">
        <%= f.submit "SAVE" %>
    </div>

<% end %>

   

app/views/contacts/edit.html.erb
<div class='wrapper'>
	<%= render 'form' %>
</div>

app/views/contacts/index.html.erb
<h1>contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Workplace</th>
    <th>Phone</th>
    <th>Email</th>
    <th>LinkedIn</th>
    <th></th>
    <th></th>
  </tr>
  
  <% @contacts.each do |contact| %>
	  <tr>
	  	<% c_name = "#{contact.first_name}  #{contact.last_name}" %>

	    <td><%= link_to c_name, contact_path(contact) %></td>
	    <td><%= contact.workplace %></td>
	    <td><%= contact.phone %></td>
	    <td><%= contact.email %></td>
	    <td><%= contact.linkedin %></td>
	    <td><%= link_to "Edit", edit_contact_path(contact) %></td>
	    <td><%= link_to "Delete", contact_path(contact), :method => :delete %></td>
	  </tr>
  <% end %>

</table>

	

app/views/contacts/new.html.erb
<div class='user-id' data-id="<%= current_user.id %>"></div>
<div id='new-contact-wrapper' class='new-item-wrapper'>
	<div index='reference-container' class='cdt-container'>
		<h1>References</h1>
		<%= render partial: "contact", collection: @contacts.is_reference || "No Contacts"%>
	</div> <!--close column -->
	
	<div index='all-contacts-container' class='cdt-container'>
	    <h1>Contacts</h1>
<!-- 	    <button id="contacts-sort">First Name</button>
	    <button id="contacts-sort-2">Last Name</button> -->
		<div id='contact-list'>
		    <%= render partial: "contact", collection: @contacts || "No Contacts"%>
	    </div>
	</div> <!--close column -->

	<div index='add-contact-container' class='cdt-container'>
		<h1>Add Contact</h1>
		<%= render 'form' %>
	</div> <!--close column -->
</div> <!--close page -->





<script type="text/javascript" charset="utf-8">
var AUTH_TOKEN = $('meta[name=csrf-token]').attr('content');

$(document).ready(function () {
	user_id = $(".user-id").data("id")
	buttonSort1()
	buttonSort2()
})

$("form").on('submit', function (e) {
	e.preventDefault()
	var $form = $(this)
	var action = $form.attr('action')
	var data = $form.serialize()
	data.authenticity_token = AUTH_TOKEN;
	$.ajax({
		url: action,
		data: data,
		datatype: 'json',
		method: 'POST', 
	    success: function (data) {
			alert('success') 
			$("#contact-list").append(data.html),
			$("#new_contact")[0].reset();
		},
		error: function (data) {
			alert('something went wrong') }
	})
})




</script>

app/views/contacts/show.html.erb
<div class='user-id' data-id="<%= @contact.user.id %>"></div>
<div class='contact-id' data-id="<%= @contact.id %>"></div>
<div id='contact-show-container' class='show-container'>
	<div class='heading-container contact-item-container'>
		<div class='edit-delete'>
		    <td><%= link_to "Edit", edit_contact_path(@contact) %></td>
		    <td><%= link_to "Delete", contact_path(@contact), :method => :delete %></td>
		</div> <!-- close container -->

		<!-- <span class="headline pg-btn btn-previous"><i class="fa fa-long-arrow-left"></i></span> -->
    	<h1 id='name-position' class='headline'><%= @contact.first_name %> <%= @contact.last_name %> - <%= @contact.workplace %></h1>
		<!-- <span class="headline pg-btn btn-next"><i class="fa fa-long-arrow-right"></i></span> -->
	</div> <!-- close container -->

	<div id='contact-info-container'>
		<section id='contact-info-section'>
			<div><h3><%= @contact.email %></h3></div>
			<div><h3><%= @contact.phone %></h3></div>
		</section>
	</div> <!-- close container -->

	<div id='reference-container'>
		<section id='reference-section'>
			<div id='contact_reference'></div>
			<div id='reference-toggle'>
				<input type="checkbox" id="switch">
				<label id='switch-label' for="switch">Toggle</label>
			</div>
		</section>
	</div> <!-- close container -->

	<div class='linked-items'>
		<section class='linked-items-section'>
		    <div id='contact-linked-jobs' class='linked-container'>
		        <h2>LINKED JOBS</h2>
		            <% if @contact.jobs.length > 0 %>
		                <%= render partial: "jobs/job", collection: @contact.jobs || "No Linked Jobs" %>
		            <% else %>
		                <h3><%= link_to '* Link This Contact To A Job', jobs_path %></h3>
		            <% end %>
		    </div> <!-- close container -->

		    <div id='contact-linked-tasks' class='linked-container'>
	        	<h2>TASKS</h2>
	            <% if @contact.tasks.length > 0 %>
	                <%= render partial: "tasks/task", collection: @contact.tasks || "No Linked Tasks" %>
	            <% else %>
	                <h3><%= link_to '* Link This Contact To A Task', new_task_path %></h3>
	            <% end %>
		    </div> 
		</section> <!-- close section -->
	</div><!-- close linked items -->

	<div id='job-desc-container' class='job-content-container'>
		<% if @contact.notes != "" %>
			<h2> Notes </h2>
			<h3 class='descriptions'><%= @contact.notes %></h3>
		<% else %>
			<h2>This contact has no notes</h2>
			<p class='create-item'><%= link_to "add notes", edit_contact_path(@contact) %></p>
		<% end %>
	</div> <!-- close container -->


</div> <!-- close wrapper -->





























<script>



const toggleReference = function (contact) {
    // place click listener on toggle
    $('#switch').on('click', function() {
        // route changing to new status
        console.log('switch listen')
        contact.reference = !contact.reference;
        $.get(`/contacts/${contact_id}/add_reference?q=${contact.reference}`, function(data) {
            $('#contact_reference').html(contact.referenceString(contact.reference))
        })
    })
}

const displayRefStatus = function (contact) {
	$('#contact_reference').html(contact.referenceString())
	let tog = document.getElementById("switch")
    tog.checked = contact.reference;
}

$( document ).on('turbolinks:load', function() {
	user_id = $(".user-id").data("id")
	contact_id = $(".contact-id").data("id")

	$.get(`/contacts/${contact_id}.json`, function(data) {
		contact = new Contact(data, user_id)
	    displayRefStatus(contact)
		toggleReference(contact)

	});
})




</script>