config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  resources :contacts
  resources :documents
  resources :companies

  resources :jobs do
    patch :link_contact
    patch :link_document

    resources :contacts, module: 'jobs', only: [] do
      delete :unlink
    end

    resources :documents, module: 'jobs', only: [] do
      delete :unlink
    end
  end

  resources :tasks do
    patch :link_contact
    patch :link_document
    patch :link_job
    patch :link_company

    resources :contacts, module: 'tasks', only: [] do
      delete :unlink
    end

    resources :documents, module: 'tasks', only: [] do
      delete :unlink
    end    

    resources :jobs, module: 'tasks', only: [] do
      delete :unlink
    end

    resources :companies, module: 'tasks', only: [] do
      delete :unlink
    end
  end

  get '/contacts/:contact_id/add_reference', to: 'contacts#add_reference', as: 'add_reference'
  get '/contacts/sort', to: 'contacts#sort', as: 'contacts_sort'

  get '/jobs/:job_id/applied', to: 'jobs#applied', as: 'applied'
  get '/jobs/:job_id/archived', to: 'jobs#archived', as: 'archived'
  get '/jobs/:job_id/next', to: 'jobs#next', as: 'user_job_next'
  get '/jobs/:job_id/previous', to: 'jobs#previous', as: 'user_job_previous'
  
  get '/tasks/:task_id/completed', to: 'tasks#completed', as: 'completed'

  root 'static_pages#home'
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  belongs_to :user

  has_many :company_documents	
  has_many :companies, through: :company_documents	

  has_many :job_documents
  has_many :jobs, through: :job_documents

  has_many :task_documents
  has_many :tasks, through: :task_documents

  validates :title, presence: true
  validates_associated :user
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :user

  has_many :company_jobs
  has_many :companies, through: :company_jobs
  
  has_many :job_contacts
  has_many :contacts, through: :job_contacts

  has_many :job_documents
  has_many :documents, through: :job_documents
  
  has_many :task_jobs
  has_many :tasks, through: :task_jobs

  validates :company, :position, presence: true
  validates_associated :user

  scope :applied, -> { where("applied = ? ", true) }


  def next
    join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
    where_query = 'jobs.id > ? AND jobs.user_id = ?'

    job = Job.joins(join_query).where(where_query, id, user_id).first
    job ||= Job.find_by(user_id: user_id)
  end

  def previous
    join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
    where_query = 'jobs.id > ? AND jobs.user_id = ?'

    job = Job.joins(join_query).where(where_query, id, user_id).first
    job ||= Job.find_by(user_id: user_id)
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < ApplicationController
  before_action :set_document, only: %i[show edit update destroy]

  def index
    @document = Document.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @document, status: 200 }
    end
  end


  def unlink_document
    d_id = params[:document_id]
    j_id = params[:job_id]
    document = Document.find(d_id)
    job = Job.find(j_id)
    job.documents.delete(document)
    respond_to do |format|
         format.json { render json: document, status: 200 }
       end
  end

  def new
    @document = Document.new(user: current_user)
    @documents = current_user.documents
  end

  def create
    @document = Document.create(document_params)
    @document.user = current_user
    @document.save
    respond_to do |format|
      format.json { render json: { html: render_to_string('documents/_document.html.erb', layout: false, locals: { document: @document }) } }
    end
  end

  def show
    @document = Document.find_by(id: params[:id], user_id: current_user.id)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @document, status: 200 }
    end
  end

  def edit; end

  def update
    flash[:notice] = 'Document updated'
    @document.update(document_params)
    redirect_to document_path(@document)
  end

  def destroy
    flash[:notice] = 'Document destroyed'
    @document.destroy
    redirect_to new_document_path
  end

  private

  def document_params
    params.require(:document).permit(:title, :url, :description, :doctype)
  end

  def set_document
    @document = Document.find(params[:id] || params[:document_id])
  end
end

app/controllers/jobs/documents_controller.rb
# frozen_string_literal: true
module Jobs
  class DocumentsController < ApplicationController
    

    def unlink
      document = Document.find(params[:document_id])
      job = Job.find(params[:job_id])
      job.documents.delete(document)
      respond_to do |format|
        format.json { render json: document, status: 200 }
      end
    end
  end
end

app/controllers/tasks/documents_controller.rb
# frozen_string_literal: true
module Tasks
  class DocumentsController < ApplicationController
    

    def unlink
      # binding.pry
      @document = Document.find(params[:document_id])
      task = Task.find(params[:task_id])
      task.documents.delete(@document)
      respond_to do |format|
        format.json { render json: @document, status: 200 }
      end
    end
  end
end

app/helpers/documents_helper.rb
# frozen_string_literal: true

module DocumentsHelper
  def groupDoctype(documents)
    documents.group_by(&:doctype)
  end
end

app/views/documents/_document.html.erb
<h3><%= link_to "<li>#{document.title}</li><br>".html_safe, document_path(document), :class => "bullet-item" %></h3>

app/views/documents/_document_dropdown.html.erb
<div>
	<%= form_for @job, url: job_link_document_path(@job), :html => {:id => "add-document", :class => "link-field", :method => :post} do |f| %>

		<p><%= f.collection_select :document_ids, @job.user.documents, :id, :title, {:include_blank => 'choose document'} %></p>	

		<%= f.submit "Link Document", {id: 'btn-add-document', class: 'btn-add-job-item'} %>

	<% end %>
</div>

app/views/documents/_document_task_dropdown.html.erb
<div>
	<%= form_for @task, url: task_link_document_path(@task), :html => {:id => "add-document", :class => "link-field", :method => :patch} do |f| %>

		<p><%= f.collection_select :document_ids, @task.user.documents, :id, :title, {:include_blank => 'choose document'} %></p>	

		<%= f.submit "Link Document", {id: 'btn-add-document', class: 'btn-add-task-item'} %>

	<% end %>
</div>

app/views/documents/_form.html.erb
<%= form_for [@document] do |f| %>

	<div class='field'>
		<%= f.label :title, "Title" %><br>
		<%= f.text_field :title, id: 'title', :required => true  %>
	</div>

	<div class='field'>
		<%= f.label :description, "Description" %><br>
		<%= f.text_field :description, id: 'description' %>
	</div>

	<div class='field'>
		<%= f.label :doctype, "Doctype" %><br>
		<%= f.select :doctype, [ 'Resume','Cover Letter','Correspondence', 'Examples', 'Other' ], :prompt => 'Select One', :required => true %>
	</div>

	<div class='field'>
		<%= f.label :url, "Link" %><br>
		<%= f.text_field :url, id: 'url' %>
	</div>

	<div class='actions'>
		<%= f.submit "SAVE" %>
	</div>

<% end %>

app/views/documents/edit.html.erb
<div class='wrapper'>
	<%= render 'form' %>
</div>

app/views/documents/index.html.erb
<h1>Documents</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

  <% @documents.each do |document| %>
	  <tr>
	    <td><%= link_to document.description, document_path(document) %></td>
	    <td>document</td>

	    <td><%= link_to "Edit", edit_document_path(document) %></td>
	    <td><%= link_to "Delete", document_path(document), :method => :delete %></td>
	  </tr>
  <% end %>

</table>

	

app/views/documents/new.html.erb
<div id='new-document-wrapper' class='new-item-wrapper'>
	<div index='doctype-container' class='cdt-container'>
		<% if @documents.length > 0 %>
			<% groupDoctype(@documents).each do |d| %>
				<h1 class='doctype-grp'><%= d[0].pluralize(2) %></h1>
				<% d[1].each do |doc| %>
					<h3><%= link_to "<li>#{doc.title}</li><br>".html_safe, document_path(doc), :class => "bullet-item" %></h3>
				<% end %> 
			<% end %>
		<% else %>
			<h1>DOCUMENTS BY TYPE</h1>
		<% end %>
	</div> <!-- close column -->

	<div index='alldocs-container' class='cdt-container'>
	    <h1>All Documents</h1>
		<div id='document-list'>
		    <%= render partial: "document", collection: @documents || "No Documents"%>
	    </div>
	</div> <!-- close column -->
	
	<div index='add-doc-container' class='cdt-container'>
		<h1>Add Document</h1>
		<%= render 'form' %>
	</div> <!-- close column -->
</div> <!-- close wrapper -->




<script type="text/javascript" charset="utf-8">

var AUTH_TOKEN = $('meta[name=csrf-token]').attr('content');

// $("form").on('submit', function (e) {
$(document.body).on('submit', "form", function(e) {

	e.preventDefault()
	var $form = $(this)
	var action = $form.attr('action')
	var data = $form.serialize()
	data.authenticity_token = AUTH_TOKEN;

	$.ajax({
		url: action,
		data: data,
		datatype: 'json',
		method: 'POST', 
	    success: function (data) {
			alert('success') 
			$("#document-list").append(data.html),
			$("#new_document")[0].reset();
		},
		error: function (data) {
			alert('something went wrong') }
	})
})





</script>

app/views/documents/show.html.erb
<div id='document-show-container' class='show-container'>
        <div class='heading-container document-item-container'>
            <div class='edit-delete'>
                <td><%= link_to "Edit", edit_document_path(@document) %></td>
                <td><%= link_to "Delete", document_path(@document), :method => :delete %></td>
            </div>
            <!-- <span class="headline pg-btn btn-previous"><i class="fa fa-long-arrow-left"></i></span> -->
            <h1 id='document-title' class='headline'><%= @document.title %></h1>
            <!-- <span class="headline pg-btn btn-next"><i class="fa fa-long-arrow-right"></i></span> -->
        </div> <!-- close container -->

        <div id='doc-info-container'>
            <section id='doc-info-section'>
                <div><h3 class='link-to'><a href="<%= @document.url %>" target="_blank">Go to Document</a></h3></div>
                <div><h3>Last update: <%= format_date(@document.updated_at) %></h3></div>
            </section>
        </div> <!-- close container -->

        <div id='doc-description-container'>
            <h3>Description: <%= @document.description %></h3>
        </div> <!-- close container -->


    <div class='linked-items'>
        <section class='linked-items-section'>
            <div id='document-linked-jobs' class='linked-container'>
                <h2>LINKED JOBS</h2>
                <div class='linked-items'>
                    <% if @document.jobs.length > 0 %>
                        <%= render partial: "jobs/job", collection: @document.jobs || "No Linked Jobs" %>
                    <% else %>
                        <h3><%= link_to '* Link This Document To A Job', jobs_path %></h3>
                    <% end %>
                </div>
            </div> <!-- close container -->

            <div id='document-linked-tasks' class='linked-container'>
                <h2>LINKED TASKS</h2>
                <div class='linked-items'>
                    <% if @document.tasks.length > 0 %>
                        <%= render partial: "tasks/task", collection: @document.tasks || "No Linked Tasks" %>
                    <% else %>
                        <h3><%= link_to '* Link This Document To A Task', new_task_path %></h3>

                    <% end %>
                </div>
            </div>  <!-- close container -->
        </section>
    </div> <!-- close linked items -->
</div> <!-- close wrapper -->