config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  resources :contacts
  resources :documents
  resources :companies

  resources :jobs do
    patch :link_contact
    patch :link_document

    resources :contacts, module: 'jobs', only: [] do
      delete :unlink
    end

    resources :documents, module: 'jobs', only: [] do
      delete :unlink
    end
  end

  resources :tasks do
    patch :link_contact
    patch :link_document
    patch :link_job
    patch :link_company

    resources :contacts, module: 'tasks', only: [] do
      delete :unlink
    end

    resources :documents, module: 'tasks', only: [] do
      delete :unlink
    end    

    resources :jobs, module: 'tasks', only: [] do
      delete :unlink
    end

    resources :companies, module: 'tasks', only: [] do
      delete :unlink
    end
  end

  get '/contacts/:contact_id/add_reference', to: 'contacts#add_reference', as: 'add_reference'
  get '/contacts/sort', to: 'contacts#sort', as: 'contacts_sort'

  get '/jobs/:job_id/applied', to: 'jobs#applied', as: 'applied'
  get '/jobs/:job_id/archived', to: 'jobs#archived', as: 'archived'
  get '/jobs/:job_id/next', to: 'jobs#next', as: 'user_job_next'
  get '/jobs/:job_id/previous', to: 'jobs#previous', as: 'user_job_previous'
  
  get '/tasks/:task_id/completed', to: 'tasks#completed', as: 'completed'

  root 'static_pages#home'
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_many :company_jobs
  has_many :jobs, through: :company_jobs

  has_many :company_contacts
  has_many :contacts, through: :company_contacts

  has_many :company_documents
  has_many :documents, through: :company_documents
  
  has_many :company_tasks
  has_many :tasks, through: :company_tasks

  validates_associated :user

  # def next
  #   join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
  #   where_query = 'jobs.id > ? AND jobs.user_id = ?'

  #   job = Job.joins(join_query).where(where_query, id, user_id).first
  #   job ||= Job.find_by(user_id: user_id)
  # end

  # def previous
  #   join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
  #   where_query = 'jobs.id > ? AND jobs.user_id = ?'

  #   job = Job.joins(join_query).where(where_query, id, user_id).first
  #   job ||= Job.find_by(user_id: user_id)
  # end

end

app/models/company_contact.rb
class CompanyContact < ApplicationRecord
  belongs_to :company
  belongs_to :contact
end

app/models/company_document.rb
class CompanyDocument < ApplicationRecord
  belongs_to :company
  belongs_to :document
end

app/models/company_job.rb
class CompanyJob < ApplicationRecord
  belongs_to :company
  belongs_to :job
end

app/models/company_task.rb
class CompanyTask < ApplicationRecord
  belongs_to :company
  belongs_to :task
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :user
  
  has_many :job_contacts
  has_many :jobs, through: :job_contacts

  has_many :company_contacts
  has_many :companies, through: :company_contacts

  has_many :task_contacts
  has_many :tasks, through: :task_contacts

  scope :is_reference, -> { where('reference = ?', true) }

  validates :email, :first_name, presence: true
  validates_associated :user

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  belongs_to :user

  has_many :company_documents	
  has_many :companies, through: :company_documents	

  has_many :job_documents
  has_many :jobs, through: :job_documents

  has_many :task_documents
  has_many :tasks, through: :task_documents

  validates :title, presence: true
  validates_associated :user
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :user

  has_many :company_jobs
  has_many :companies, through: :company_jobs
  
  has_many :job_contacts
  has_many :contacts, through: :job_contacts

  has_many :job_documents
  has_many :documents, through: :job_documents
  
  has_many :task_jobs
  has_many :tasks, through: :task_jobs

  validates :company, :position, presence: true
  validates_associated :user

  scope :applied, -> { where("applied = ? ", true) }


  def next
    join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
    where_query = 'jobs.id > ? AND jobs.user_id = ?'

    job = Job.joins(join_query).where(where_query, id, user_id).first
    job ||= Job.find_by(user_id: user_id)
  end

  def previous
    join_query = 'LEFT OUTER JOIN users ON user_id = users.id'
    where_query = 'jobs.id > ? AND jobs.user_id = ?'

    job = Job.joins(join_query).where(where_query, id, user_id).first
    job ||= Job.find_by(user_id: user_id)
  end
end

app/models/job_contact.rb
# frozen_string_literal: true

class JobContact < ApplicationRecord
  belongs_to :contact
  belongs_to :job
end

app/models/job_document.rb
# frozen_string_literal: true

class JobDocument < ApplicationRecord
  belongs_to :job
  belongs_to :document
end

app/models/session.rb
# frozen_string_literal: true

class Session < ApplicationRecord
  validates :username, :password_digest, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user

  has_many :company_tasks
  has_many :companies, through: :company_tasks

  has_many :task_contacts
  has_many :contacts, through: :task_contacts

  has_many :task_documents
  has_many :documents, through: :task_documents
  
  has_many :task_jobs
  has_many :jobs, through: :task_jobs

  validates :title, presence: true
  validates_associated :user

  scope :completed_false, -> { where('completed = ?', false) }
  scope :completed_true, -> { where('completed = ?', true) }

  scope :overdue, -> { where('due_date < ?', DateTime.now.end_of_day) }
  scope :upcoming, -> { where('due_date >= ?', DateTime.now.beginning_of_day) }
  scope :today, -> { where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day) }
end

app/models/task_contact.rb
# frozen_string_literal: true

class TaskContact < ApplicationRecord
  belongs_to :task
  belongs_to :contact
end

app/models/task_document.rb
# frozen_string_literal: true

class TaskDocument < ApplicationRecord
  belongs_to :task
  belongs_to :document
end

app/models/task_job.rb
# frozen_string_literal: true

class TaskJob < ApplicationRecord
  belongs_to :task
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

 attr_writer :login

  has_many :contacts, -> { order(last_name: :desc) }
  has_many :documents
  has_many :jobs
  has_many :tasks
  has_many :companies

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
    if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
    end
  end
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
  def formatted_name(contact)
    "#{contact.first_name} #{contact.last_name}".titlecase
  end
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true

module JobsHelper
  def truncate_desc(desc)
    truncate_desc(desc, length: 10, omission: '...')
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_navigation.html.erb
<div id='nav-container'>

  <% if user_signed_in? %>
    <ul>
      <li><a href="<%= user_path(current_user) %>"/>Home</a></li>
      <li class="mobile-no-show"><a href="<%= jobs_path %>"/>Jobs</a></li>
      <li class="mobile-no-show"><a href="<%= new_task_path %>"/>Tasks</a></li>
      <li class="mobile-no-show"><a href="<%= new_contact_path %>"/>Contacts</a></li>
      <li class="mobile-no-show"><a href="<%= new_document_path %>"/>Docs</a></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <li id='user-greeting'><a href="<%= user_path(current_user) %>"/>hi, <%= current_user.username %></a></li>
    </ul>
  <% else %> 
    <ul>      
      <li><%= link_to "Sign up", new_user_registration_path %></li>   
      <li><%= link_to "Login", new_user_session_path %></li>
    </ul>
  <% end -%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareerPath</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="turbolinks-visit-control" content="reload">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
  </head>

  <body>

    <%= render 'layouts/navigation' %>


    <div class="container"  role="main">
      
      <div id="flash">
        <% flash.each do |key,value| %>
          <div class="flash-alert <%= alert_class(key) %>"><%= value %></div>
        <% end %>
      </div>



      <%= yield %>  

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<div class='error-container'>

	<% if target %>
		<% if target.errors.any? %> 
			<div id="error_explanation">
				<h2 id='error-title'><%= pluralize(target.errors.count, "error") %> prohibited this action</h2>
					<% target.errors.full_messages.each do |msg| %>
						<p>* <%= msg %></p>
					<% end %>
			</div>
		<% end %>
	<% end %>

</div>